// Generated by SHIP before `npm publish`; this checked-in copy holds placeholders until then.
export const RELAY_ORIGIN = "wss://sesh-relay.example.workers.dev";
export const VIEWER_ORIGIN = "https://sesh.example.dev";
